# Generated by Django 4.2.6 on 2023-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='y_position',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='z_position',
        ),
        migrations.AddField(
            model_name='marker',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Markup',
        ),
    ]
