# Generated by Django 4.2.6 on 2023-11-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_hotspot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotspot',
        ),
    ]
