# Generated by Django 4.2.6 on 2023-12-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_hotspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.floorplan')),
            ],
        ),
    ]
