# Generated by Django 4.2.6 on 2023-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_hotspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='y',
            field=models.IntegerField(),
        ),
    ]
