# Generated by Django 4.2.6 on 2023-12-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_hotspot_x_alter_hotspot_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='hotspot',
            name='images',
            field=models.ManyToManyField(to='myapp.imagemodel'),
        ),
    ]
