# Generated by Django 4.2.6 on 2023-12-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_imagemodel_hotspot_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='images',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.image'),
        ),
    ]
