# Generated by Django 4.2.6 on 2023-12-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_hotspot_images_hotspot_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='images',
            new_name='image',
        ),
    ]
