# Generated by Django 4.2.6 on 2023-12-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_image_hotspot_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='images',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='image',
            field=models.ManyToManyField(to='myapp.imagemodel'),
        ),
    ]
