# Generated by Django 4.2.6 on 2023-12-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_hotspot_images_hotspot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='image',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspots', to='myapp.image'),
        ),
    ]
