# Generated by Django 4.2.6 on 2023-12-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_hotspot_image_hotspot_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hotspot')),
            ],
        ),
    ]
