# Generated by Django 4.2.6 on 2023-12-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_hotspotimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotspotImage',
        ),
    ]
