# Generated by Django 4.2.6 on 2023-12-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_hotspot_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='image',
            field=models.ImageField(null=True, upload_to='360_images/'),
        ),
    ]
