# Generated by Django 4.2.6 on 2023-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_hotspot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='image',
            field=models.ImageField(null=True, upload_to='hotspot_images/'),
        ),
    ]
