# Generated by Django 4.2.6 on 2023-12-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_hotspot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='image',
        ),
    ]
