# Generated by Django 4.2.6 on 2023-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_hotspot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotspot_images/'),
        ),
    ]
