# Generated by Django 4.2.6 on 2023-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_hotspot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='image',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='image_360',
            field=models.ImageField(blank=True, null=True, upload_to='hotspot_360_images/'),
        ),
    ]
