# Generated by Django 4.2.6 on 2023-12-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_hotspot_image_hotspot_image_360'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='image_360',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotspot_images/'),
        ),
    ]
