# Generated by Django 4.2.6 on 2023-12-19 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_hotspot_image_360_hotspot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
        ),
    ]
